add function testTor and checkIp

diff --git a/src/functions b/src/functions
--- a/src/functions
+++ b/src/functions
@@ -83,14 +83,12 @@ restoreFiles() {
   local dir f
   dir=$backup_dir
   [[ -z $dir ]] && die "$dir no found"
-  cpy $dir/grub /etc/default/grub
   cpy $dir/hostname /etc/default/hostname
   cpy $dir/hosts /etc/hosts
   cpy $dir/resolv.conf /etc/resolv.conf
   cpy $dir/rules-save /var/lib/nftables/rules-save
   cpy $dir/sysctl.conf /etc/sysctl.conf
   cpy $dir/torrc /etc/tor/torrc
-  cpy $dir/.config /usr/src/linux-4.19.9-gentoo/.config
   cpy $dir/.ssh $ssh_dir
   for f in $other_host_files ; do
     cpy $dir/${f##*/} $f
@@ -211,4 +209,37 @@ writeHost() {
   [[ ! -z $xorg ]] && forXorg "$old" "$rule"
   otherHostFiles "$rule"
   $HOSTNAME $new
+}
+
+#######################################################
+# Check network
+
+checkIp() {
+  local external_ip ip_1 ip_2
+  printf "%s %s\\n" \
+    "==>" "Checking your public IP, please wait..."
+
+  ip_1=$(curl -s -m 10 https://ipinfo.io)
+  ip_2=$(curl -s -m 10 https://ip-api.com)
+
+  if external_ip="$ip_1" || external_ip="$ip_2" ; then
+
+  printf "%s\\n" "$external_ip" | tr -d '"{}' | sed 's/ //g'
+else
+  printf "%s\\n" "[ failed ] curl: HTTP request error"
+  exit 1
+fi
+}
+
+testTor() {
+  local url
+  url="https://check.torproject.org/"
+  curl -s -m 10 -L "$url" | cat | tac | grep -q 'Congratulations'
+  if [ $? -eq 0 ] ; then
+    echo "[+] Tor is working properly"
+    checkIp
+  else
+    echo "[-] Unfortunately, Tor is no working"
+    exit 0
+  fi
 }
